### ISSUE TITLE
Create a public plugin API for adding tracers

### ISSUE THREAD

**Issue by disintegrator** [benthosdev/benthos#1224]
This is a feature request for adding the following API to make it easy to create new tracer plugins:

```
func service.RegisterTracer(name string, spec *service.ConfigSpec, ctor service.TracerConstructor) error
```

**Comment by disintegrator** [comment]
@Jeffail alongside that request, it would be great if tracers got passed a (shutdown) context to the their `Close` method. i.e. `Close(ctx context.Context) error`. Currently `tracer.Type` does not support this.

**Comment by Jeffail** [comment]
Done, I've decided to change the plugin implementations so they only return a `trace.TracerProvider`. The interface doesn't itself have a shutdown method but we look for one with an interface assertion during termination. I've also put the work in to isolate the provider at the manager level so that we no longer need to globally register them: https://github.com/benthosdev/benthos/commit/76f868103dc5ef96ffbc16006c39a7867024793b, that'll make it less confusing for users of the stream builder API.

**Comment by disintegrator** [comment]
Thanks @Jeffail!
