### ISSUE TITLE
aws_s3 input causes benthos to exit when it encounters an empty file

### ISSUE THREAD

**Issue by skolem-dan** [benthosdev/benthos#1254]
I've got an `aws_s3` input set up to follow an SQS queue for updates, meaning Benthos should continue running indefinitely while it waits for new messages. Very rarely, an empty (0 byte) log file will be created in the S3 bucket, which causes Benthos to immediately exit. No processors are run against the message before Benthos shuts down, so it's not possible to handle the error with code.

Sample input configuration:
```
input:
  aws_s3:
    region: ${BENTHOS_SQS_REGION}
    codec: gzip/lines
    sqs:
      url: https://sqs.${BENTHOS_SQS_REGION}.amazonaws.com/${BENTHOS_SQS_ID}/${BENTHOS_SQS_NAME}
```

Sample input file:
```
```

Log output:
```
14:36:03.950 {"label":"","level":"info","msg":"Downloading S3 objects found in messages from SQS: https://sqs.us-east-1.amazonaws.com/111111111111/queue-name","path":"root.input","time":"2022-05-10T19:36:03Z"}
14:36:04.070 {"label":"","level":"debug","msg":"Pushing SQS notification back into the queue due to error: EOF","path":"root.input","time":"2022-05-10T19:36:04Z"}
14:36:04.075 {"label":"","level":"debug","msg":"Waiting for pending acks to resolve before shutting down.","path":"root.input","time":"2022-05-10T19:36:04Z"}
14:36:04.075 {"label":"","level":"debug","msg":"Pending acks resolved.","path":"root.input","time":"2022-05-10T19:36:04Z"}
14:36:04.082 {"level":"info","msg":"Launching a benthos instance, use CTRL+C to close.","time":"2022-05-10T19:36:04Z"}
14:36:04.082 {"level":"info","msg":"Pipeline has terminated. Shutting down the service.","time":"2022-05-10T19:36:04Z"}
```

**Comment by Jeffail** [comment]
Hey @skolem-dan, thanks for raising this, I have a speculative fix here: https://github.com/benthosdev/benthos/commit/54ec38b6c979c889fce168a607c10932f388d5f2, it will prevent Benthos from gracefully terminating but the SQS message that triggers the object consumption will still be "rejected", so it's visibility timeout set to 0 and therefore retried.

You'll therefore still need to have a DLQ or max retries configured on the SQS side in order to handle these cases properly.

I haven't reproduced this locally yet, let me know if you get a chance to try the fix.

**Comment by skolem-dan** [comment]
I just had a chance to replicate this issue again in a test environment on the :4.0.0 Docker image, and I'm thrilled to report that when I run the same test on :edge, Benthos logs the expected error and keeps on running! This should give me everything I need. Thanks for the super-fast fix!

**Comment by Jeffail** [comment]
Whoops, forgot to close this, thanks for the update @skolem-dan!
