### ISSUE TITLE
No tests found anymore when passed folder path

### ISSUE THREAD

**Issue by razor-x** [benthosdev/benthos#1258]
Running tests as documented here no longer works https://www.benthos.dev/docs/configuration/unit_testing/#running-tests

<img width="879" alt="image" src="https://user-images.githubusercontent.com/721372/168664153-c96f5598-91a3-444e-b6a0-66a5e22a0c52.png">

Reproduce with:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/721372/168664044-21744f33-9c11-444a-ac94-f611d3b0faf1.png">

(note, same results if passed `./config`)

**Comment by Jeffail** [comment]
Arrrrgggh, thanks for raising this @razor-x! We now use the same path resolution as other file target cli sub commands so `config/...` will work, as well as super wildcards like `config/**/*.yaml`, but we no longer automatically walk on directory targets. We also don't throw errors when a directory is targetted.

I think recursing when targeting a directory isn't particularly intuitive, which is probably why I was happy to get rid of it during the v4 move. However, if that were the intention (struggling to remember now) then I should have added it as an entry to the change log and migration guide as an intentional break.

So I think for starters, regardless of what action we take here, the documentation should be updated to show wildcard and triple dot syntax. Then we can either add an entry to the change log and migration guide retrospectively and maybe throw an error when `benthos test` is used to target directories, hopefully making it easier for users to catch this when migrating.

Alternatively, we can fix the behaviour and keep it around as an undocumented feature.

**Comment by Jeffail** [comment]
I decided in the end to go down the docs and update migration guide approach: https://github.com/benthosdev/benthos/commit/c2bde88b82281d89142e55c40ca32cf24af28eb3. Happy to revise in future if we decide there's a good reason to add it back in, but for now `./foo/...` works the same way (and is more explicit).
