### ISSUE TITLE
Allow multiple batch input in tests

### ISSUE THREAD

**Issue by sapk** [benthosdev/benthos#1289]
Hi, firstly, thanks for this great and neat tool.

I would like to be able to test how a processor is working across multiple batch and this need to be able to define multiple input batch like the output batch.

My use case is verifying that my processors are working by batch and not across them by skipping some message in one batch but not in an other batch. Like a deduplication but by batch and not across them.

This would mean a breaking change by switching configuration `tests[].input_batch[]` to `tests[].input_batch[][]` similar to output batch structure.

I would gladly contribute to do this change but I would need your go before since it is a breaking change.

**Comment by Jeffail** [comment]
Hey @sapk, we can take a look. I would suggest that we add a new field called something like `input_batches` in order to be backwards compatible, it'd be nice to be able to continue using `input_batch` when it's all that's needed. The difficulty here would likely be expanding the tests to account for multiple batches.

**Comment by sapk** [comment]
PR merged this issue can be closed. Thanks for your review.
