### ISSUE TITLE
Disable streams mode HTTP endpoint prefixing

### ISSUE THREAD

**Issue by narzdavid** [benthosdev/benthos#1323]
Our project is currently using streams mode to setup multiple http webhooks in a single deployment. We are refactoring our streams such that the http_server declarations are inline in the streams file instead of uses the resources file. However, we met a strange behavior:
- when the stream is declared using an input resource, the endpoint exposed is 
`/$path` 
- when the stream is declared using inline http_server object, then endpoint exposed is 
`${streamFileName}/$path`

Please refer to this project as an example:
https://github.com/narzdavid/benthos_http_server
If you run `curl localhost:4195/endpoints` against benthos, the following endpoints are exposed: 

```
{
...

  "/http_server_weird_endpoint/i_dont_want_this_prefix": "Post a message into Benthos.",
...
  "/normal_endpoint": "Post a message into Benthos.",

}
```

Is this an expected behavior? We could not find an explanation for this behavior from the current docs :( 
We would like to declare the input object inline input in the stream so that we can template it, but we also have to make sure the endpoint exposed is a root endpoint.

**Comment by Jeffail** [comment]
Done: https://github.com/benthosdev/benthos/commit/c0b2f7bf371e46f63bf4cf86e491235dee75e149, I've updated the docs for streams mode as well to clarify the behaviour. In your example the `/normal_endpoint` endpoint isn't prefixed because it's registered by a resource that is owned by the whole service rather than the individual stream.
