### ISSUE TITLE
Dynamic output and input summary endpoint is broken in v4

### ISSUE THREAD

**Issue by nibbleshift** [benthosdev/benthos#1398]
In v4 the HandleList function is producing an error when attempting to marshal the list of configured inputs/outputs.   This is because of a discrepancy between yaml/json and the json object returned has a json.RawMessage field that actually has yaml in it.

**Comment by nibbleshift** [comment]
Fixed in https://github.com/benthosdev/benthos/pull/1380

**Comment by Jeffail** [comment]
Hey @nibbleshift I've solved this specifically for the list endpoint by unmarshalling into a structured form as part of the response: https://github.com/benthosdev/benthos/commit/c151d57b32a51011feca9114ad633ddccd0dbfb0, I've also added a `config_raw` field that contains the raw config of the component. Decided to go this way so that CRUD hitting directly on the individual named components still returns the raw config provided to avoid confusion.
