### ISSUE TITLE
why deprecate the parquet component

### ISSUE THREAD

**Issue by skyoct** [benthosdev/benthos#1454]
Hello,
I see in the document that the request is marked as deprecated. This component is being used in our project. What is the main reason for deprecated.

**Comment by mihaitodor** [comment]
Hey @skyoct, the goal was to eventually stop using github.com/xitongsys/parquet-go as the underlying library and switch to github.com/segmentio/parquet-go to have better parquet support. See more details in #1205. In order to have a smooth transition, the `parquet` processor has been deprecated and 2 new ones have been added: `parquet_decode` and `parquet_encode`. It would be super-helpful if you can test those out and report back if you have any issues with them.

**Comment by skyoct** [comment]
@mihaitodor parquet_encode and parquet_decode component can be used in the production environment？

**Comment by mihaitodor** [comment]
@skyoct Yep. Please try it and report back if you encounter any issues.
