### ISSUE TITLE
add option on output cassandra to write using async batches for performance reasons

### ISSUE THREAD

**Issue by peczenyj** [benthosdev/benthos#1465]
Hello

currently the component output cassandra handle a batch of messages using a `unlogged batch`. However, this may not be efficient, as I can read from our cassandra logs:

> "Unlogged batch covering 52 partitions detected against table [xxx.yyy]. You should use a logged batch for atomicity, or asynchronous writes for performance."

From https://foundev.medium.com/cassandra-batch-loading-without-the-batch-keyword-40f00e35e23e

> Unlogged batches require the coordinator to do all the work of managing these inserts, and will make a single node do more work. Worse if the partition keys are owned by other nodes then the coordinator node has an extra network hop to manage as well. The data is not delivered in the most efficient path.

The suggestion is to use async writes instead unlogged batches if there are no correlation in terms of partition keys between the messages.

Here is an example from the go driver

https://pkg.go.dev/github.com/gocql/gocql#hdr-Executing_multiple_queries_concurrently

I think we can add an option like `async_batch` that does not use unlogger batches but write on individual goroutines.

**Comment by Jeffail** [comment]
Hey @peczenyj, I've done a bit of digging into the original implementation and I actually think using unlogged was due to a misunderstanding of batch insert mechanisms. As far as I can tell we don't need to send unlogged batches at all so I've changed the behaviour to send logged batches instead.

I've also looked into possible solutions if we wanted to perform batched sends as async requests instead of batches and because we already have a `max_in_flight` parameter you can get away with just not batching at all, and if your data is already batched from the input use a `split` processor on the output.

Fix is here: https://github.com/benthosdev/benthos/commit/11f99d1ba55286144752a08aea0e410ea5b66a46

**Comment by peczenyj** [comment]
I tryed some manual benchmarks and increasing the max_in_flight was changing nothing.

let me provide a real benchmark test with some results
