### ISSUE TITLE
How do I use a blobl file in my benthos.yaml config?

### ISSUE THREAD

**Issue by ian-lewis-d** [benthosdev/benthos#1524]
I'm new to Benthos and enjoying getting to know it. Thanks for creating such an awesome tool.

I'm a bit confused about how to bring in a blobl mapping file to use inside my benthos.yaml config.

Here https://www.benthos.dev/docs/guides/bloblang/about#import-maps it says `It's possible to import maps defined in a file with an import statement`. But exactly where do I put the import statement? I just get an error if it is at the top of the benthos.yaml file.

`target_mapping` seems to exist only for tests.

There are many examples of using maps but I can't see anywhere that clearly explains how to import and use them.

**Comment by mihaitodor** [comment]
Hey @ian-lewis-d, that code snippet from the link you shared is a bloblang mapping which can reside either in a [`mapping`](https://www.benthos.dev/docs/components/processors/mapping) or [`mutation`](https://www.benthos.dev/docs/components/processors/mutation) processor within your [`input.processors`](https://www.benthos.dev/docs/components/inputs/about) or [`pipeline.processors`](https://www.benthos.dev/docs/components/processors/about) (I'll raise a PR to replace `bloblang` with `mapping` / `mutation`, since the `bloblang` processor is deprecated now) or [`output.processors`](https://www.benthos.dev/docs/components/outputs/about) or other subelements which support processors.

**Comment by ian-lewis-d** [comment]
Thank you for your answer.

I can see now that some of my answers are in the text but not in the examples which is what I was looking at.

I have based a recursive mapping on the one here: https://www.benthos.dev/docs/guides/bloblang/walkthrough#reusable-mappings

The file import seems to work but I am seeing parse errors.

`level=error msg="Config lint error" @service=benthos lint="/benthos.yaml(37,17) line 1 char 1: failed to parse import './example.blobl'\n  |\n1 | from \"./example.blobl\"\n  | ^---\n\n./example.blobl: line 2 char 10: expected query\n  |\n2 |     root = match {\n  |          ^---"`

I'm using: `- mapping: from "./example.blobl"` in my processor

**Comment by ian-lewis-d** [comment]
Thank you for a super clear example. 

I think it may be a C&P issue so I'm going to clean up the blobl file now and try again.
