### ISSUE TITLE
Input kafka, output snowflake_put fails, "Received unexpected Snowpipe response status: 401"

### ISSUE THREAD

**Issue by niclasgrahm** [benthosdev/benthos#1549]
Hello!

I'm trying to use the snowflake_put output to automatically call a snowflake snowpipe and insert the transferred data from a stage to an actual table. I've carefully generated the private/public keys and filled in all the fields in the .yml config as per the [docs](https://www.benthos.dev/docs/components/outputs/snowflake_put#account).

The error I'm getting: 
```
benthos_snowflake_output   | level=debug msg="Calling Snowpipe with requestId=57e6eb23-b098-4b76-a0f2-97859ad393f5" @service=benthos label="" path=root.output
benthos_snowflake_output   | level=error msg="Failed to send message to snowflake_put: failed to call Snowpipe: received unexpected Snowpipe response status: 401" @service=benthos label="" path=root.output
```

Anyone have any idea on how to approach debugging this? Anybody gotten it to work and can share configuration details?

Thanks in advance!

**Comment by mihaitodor** [comment]
Hey @niclasgrahm, I’ll need more information to help you troubleshoot that (I might need to see the config), but the first thing to check is if you followed [step 4](https://docs.snowflake.com/en/user-guide/key-pair-auth.html#step-4-assign-the-public-key-to-a-snowflake-user) in the Snowflake docs to associate that key with your Snowflake user. Also, it would help a lot if you can validate that you can use their [snowsql](https://docs.snowflake.com/en/user-guide/snowsql-use.html) tool to execute a [PUT](https://docs.snowflake.com/en/user-guide-data-load.html) command using the key you generated.

**Comment by niclasgrahm** [comment]
Hi @mihaitodor, and thank you so much for taking the time!

I've associated the key with my user:
<img width="548" alt="public_key" src="https://user-images.githubusercontent.com/97113706/198707627-861a68a0-c09e-4043-9aec-16b166ef7a45.png">

I can connect to snowflake via snowsql using the private key:
<img width="1101" alt="snowsql_private_key_auth" src="https://user-images.githubusercontent.com/97113706/198707732-429ff5ca-29bd-4179-90d9-39c37febcb5e.png">

And in that same session I can perform a PUT:
<img width="969" alt="snowsql_put" src="https://user-images.githubusercontent.com/97113706/198707815-16e8b467-1d89-4a24-8575-c11bc8eff989.png">

I'd gladly supply the actual config, though that would have to happen in a different setting I suppose :)

Best regards,
Niclas

**Comment by niclasgrahm** [comment]
I'd also like to add that my current benthos/snowflake_put config successfully adds files to the stage, it fails when trying to tell snowpipe to move the data from the stage into the table.

**Comment by mihaitodor** [comment]
Hey  @niclasgrahm, you're very close to getting it to work if it's able to stage files. Unfortunately, Snowflake makes it rather awkward to troubleshoot Snowpipe failures. Here are some things to try:
- Snowpipe does offer a REST API which you can use to get some information about the errors it encountered. Have a look [here](https://www.benthos.dev/docs/components/outputs/snowflake_put#snowpipe-troubleshooting) for instructions on how to use it. The error might be cryptic in some cases, like when the compression doesn't match (see the next bullet point).
- Make sure the compression matches on both sides. To start, set `NONE` explicitly [here](https://www.benthos.dev/docs/components/outputs/snowflake_put#compression) as well as when creating the Snowpipe. Then you can use the "handsfree" one and set both to `AUTO` (the [gosnowflake](https://github.com/snowflakedb/gosnowflake) driver will gzip the payloads under the hood in this case). If that doesn't perform well, then you can configure another type of compression and compress the message batches yourself in the Benthos config using the [compress](https://www.benthos.dev/docs/components/processors/compress) processor.
- Snowflake supports [several file formats](https://docs.snowflake.com/en/sql-reference/sql/create-file-format.html), but the easiest one to use is JSON, since that's the native one that Benthos produces. If you batch messages so you get more than one JSON document in a staged file, then it's fine to simply concatenate them. Benthos lets you [archive](https://www.benthos.dev/docs/components/processors/archive) them using `format: json_array`, but then you'll need to use `STRIP_OUTER_ARRAY = TRUE` when creating the Snowpipe.
- Use `snowsql` to download one of the files from the stage and have a look at its contents. Is it in the format you expect it to be? If not, consider adding a [`log`](https://www.benthos.dev/docs/components/processors/log) processor at the output level in the Benthos config to see what Benthos is sending.
- Depending on how your Benthos input and processors are configured, the format of each message read from the input and the batching settings, the Snowpipe declaration might need to be adjusted. I think the easiest way to validate this is to run the `COPY INTO ... FROM (SELECT ...)` statement manually once you have a file in stage and make sure it works as expected.

I think this should be enough to get you going, but if you're still stuck, you can try to share some of the information you collected based on the above items and we can see how to proceed. Feel free to join the [community](https://www.benthos.dev/community) for private chats.

**Comment by niclasgrahm** [comment]
Hi! After extensive trial and error, it's now working! Thank you so much for your list of troubleshooting ideas, they were invaluable.

Unfortunately I can't pinpoint _exactly_ what my problem was; I have a hunch though that my original configuration generated an invalid jwt, which gave the 401 error when calling the snowpipe. 

I think it's also important to make sure that the snowflake user's DEFAULT role has sufficient rights on the pipe. (This is not necessarily the role specified in the benthos config!)

This configuration works for me (posting it in full here, it might help someone with similar issues):

Snowpipe:
```
CREATE OR REPLACE PIPE <PIPE_NAME> = FALSE AS
COPY INTO <DB>.<SCHEMA>.<TABLE> (RECORD_CONTENT, RECORD_METADATA) FROM (SELECT parse_json($1):RECORD_CONTENT, parse_json($1):RECORD_METADATA FROM @%<STAGE> t) FILE_FORMAT = (TYPE = JSON COMPRESSION = NONE STRIP_OUTER_ARRAY = TRUE);
```

Benthos:
```
  snowflake_put:
    account: <ACCOUNT>
    region: <REGION>
    cloud: <CLOUD>
    user: <USER>
    private_key_file: <PATH_TO_FILE>
    private_key_pass: <PWD>
    role: <ROLE>
    database: <DB>
    warehouse: <WH>
    schema: <SCHEMA>
    stage: @%<STAGE>
    path: <PATH>
    compression: NONE
    upload_parallel_threads: 4
    snowpipe: <PIPE_NAME>
    batching:
      # count: 10
      byte_size: 160000
      period: 3s
      processors:
        - archive:
            format: json_array
    max_in_flight: 4
```
