### ISSUE TITLE
how to handle input error  ?

### ISSUE THREAD

**Issue by ctbsea** [benthosdev/benthos#1672]
if config:

```
input:
  label: "xx"
  sql_raw:
    driver: mysql
    dsn: xx:xx@tcp(xxxx)/xxx?parseTime=true
    query: 'SELECT a.id a.name FROM products where id = xx '
pipeline:
   ....
output:
  .....

benthos.exe -c config.yaml
level=error msg="Failed to connect to sql_raw: Error 1054: Unknown column 'xx' in 'where clause'" @service=benthos label=xx path=root.input
level=error msg="Failed to connect to sql_raw: Error 1054: Unknown column 'xx' in 'where clause'" @service=benthos label=xx path=root.input
level=error msg="Failed to connect to sql_raw: Error 1054: Unknown column 'xx' in 'where clause'" @service=benthos label=xx path=root.input
.......
```

why does this program keep outputting error prompts? 
`level=error msg="Failed to connect to sql_raw: Error 1054: Unknown column 'xx' in 'where clause'" @service=benthos label=cal path=root.input`
non-stop
I hope that the program will terminate once an error is output. 
but I didn't find anything relevant from the docs. 
how to handle input error  ?

**Comment by mihaitodor** [comment]
Hey @ctbsea, this behaviour is by design. There's no clear way to handle such runtime error scenarios, so Benthos prefers to keep trying to connect to components until it's told to stop if all the config preflight validations passed. It's up to you to configure monitoring, alerting and, potentially, automated actions based on the metrics (or logs) that you collect.

Note: It does shut down once all the configured inputs have shut down because there's no more data to read, but this only applies to certain inputs which have a finite amount of data to read. Realtime broker inputs such as Kafka just keep on reading messages forever (unless they're wrapped in a `read_until` input).

**Comment by ctbsea** [comment]
Thanks
