### ISSUE TITLE
help for awk command to use 

### ISSUE THREAD

**Issue by dhaldergit** [benthosdev/benthos#1686]
Hi,
I need to get number of lines in for a large file (10Millions lines). 
Below code working fine for smaller size.
- label: derive_row_count
    awk:
      codec: "text"
      program: |
        {
             data = json_get("data");
             size = split(data, null, "\r\n");
             json_set("rowcount", size);
        }

Can you please let me know how can I use the below awk command in benthos yaml similar to above.
awk 'END{print NR}' file

Thanks in advance.

**Comment by mihaitodor** [comment]
Hey @dhaldergit! I'm not really sure what the issue is, but I'm assuming it might be attempting to read the entire input file in memory and it gets OOM killed. Looking at what you have in there, I wonder why you're using awk in the first place. I believe you should be able to use the `file` input with `codec: lines` (or `codec: delim:\r\n` might be needed). To count the lines and compute `rowcount`, you can use a `mapping` processor and the `count()` bloblang function. Does that help?
