### ISSUE TITLE
Provide an official docker image in AWS ECR Public repository

### ISSUE THREAD

**Issue by natenho** [benthosdev/benthos#1693]
Hi, an official updated docker image in Public ECR gallery would help several CI/CD processes that are blocked by [Docker Hub limits](https://docs.docker.com/docker-hub/download-rate-limit/#:~:text=For%20anonymous%20users%2C%20the%20rate,Enhanced%20Service%20Account%20add%2Don.).

The current workaround is to manually mirror benthos image into a private ECR repository.

Some references:

https://gallery.ecr.aws/?searchTerm=benthos
https://docs.aws.amazon.com/AmazonECR/latest/public/what-is-ecr.html

**Comment by Jeffail** [comment]
Sounds good, is there a github action we can use for this?

**Comment by natenho** [comment]
Sure, it seems that the official action might work:

https://github.com/marketplace/actions/amazon-ecr-login-action-for-github-actions

**Comment by gregfurman** [comment]
Not sure an official image in the ECR public repo is necessary since it's possible to create a [pull through cache rule](https://docs.aws.amazon.com/AmazonECR/latest/userguide/pull-through-cache-creating-rule.html#pull-through-cache-creating-rule-console) for upstream repositories. Look at the section on `For a GitHub Container Registry` and configure rules to cache the `benthos` image in a private repository in your ECR environment.

Probably a bit late to this but [AWS only announced](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-ecr-pull-through-cache-additional-upstream-registries/) additional support for upstream repos in Nov. 23.

**Comment by natenho** [comment]
@gregfurman I agree it might not be required anymore. The pull through cache feature was not available when this issue was opened.
