### ISSUE TITLE
WebAssembly support for bloblang

### ISSUE THREAD

**Issue by koladilip** [benthosdev/benthos#1724]
Is web assembly support in the roadmap?

**Comment by mihaitodor** [comment]
There's an experimental `wasm` processor [here](https://www.benthos.dev/docs/components/processors/wasm) and some additional usage notes and examples [here](https://github.com/benthosdev/benthos/tree/main/public/wasm). I also took a stab at compiling the `bloblang` package to wasm [here](https://github.com/mihaitodor/benthos-playground/tree/main/wasm/blobl-editor) (unfortunately, I couldn't use [tinygo](https://tinygo.org/) because of the OpenTelemetry package, but I'll look into fixing that).
