### ISSUE TITLE
HTTP Headers and Query parameters not case-insensitive 

### ISSUE THREAD

**Issue by webfrank** [benthosdev/benthos#1842]
Hi,
  I discovered an issue with HTTP Server meta taken from headers or query parameters. I can call an endpoint with an header like:

token: 123456

or with query parameter ?token=123456

Inside benthos the header is found like @Token (or meta("Token")) and the query parameter like @token (first letter lower-case).

I would expect to find all the headers and parameters in lower-case just to avoid any issue like this.

**Comment by Jeffail** [comment]
@webfrank it's because in the HTTP spec header keys are case insenstivie, but often normalised to be capitalised. In order to force consistency the underlying HTTP client does the case normalisation on both ends (request and response as far as I remember).

We could potentially make a breaking change to "undo" the normalisation and enforce all lowercase but I think that'd be even more confusing. You can, however, do it in config with a mapping like this: `meta = @.map_each_key(k -> k.lowercase())`

**Comment by webfrank** [comment]
Hi, thank you for the hint. BTW I think http headers and query string params should be normalized lowercase to be able to overwrite each other and to be able to pick up indifferently one or the other.
