### ISSUE TITLE
Bloblang query did not return a boolean value

### ISSUE THREAD

**Issue by mihaitodor** [benthosdev/benthos#1860]
The following works:

```coffee
root = [2, 5].filter(i -> [1,2,3].find(j -> j == i) != -1)
```

However, the following one

```coffee
root = [2, 5].filter(i -> [1,2,3].find(i) != -1)
```

throws this error:

> failed assignment (line 1): array literal: query did not return a boolean value

It doesn't seem to happen because I set `wrapScalars = false` when calling `ParamQuery` [here](https://github.com/benthosdev/benthos/blob/c98237ef41bc80d5d3235b746ca3396a4ad2789e/internal/bloblang/query/methods_structured.go#L450) (which I think is the right thing to do? I forgot what that does now) and I'm not sure what's going on...

**Comment by Jeffail** [comment]
Okay I know what's going on, bit of sad news unfortunately. We can't reliably distinguish between a query that yields a scalar to be used as a comparison (`if something { this.foo } else { this.bar }` looks the same as `this.foo`) versus an actual comparison that yields a boolean (`this.foo > 0`).

Therefore, in order to support both cases where a user can provide a simple value to compare and alternatively support a query to execute we need to have separate methods (or a parameter). We have prior art here with the `sort` and `sort_by` methods which are in a similar situation so I think new methods fits nicely.

Since these methods are marked as BETA and this is a significant issue I think it's reasonable to remove the support for boolean queries and add new methods `find_by` and `find_all_by` which take care of that use case. Removing the ability from `find` and `find_by` makes it possible to do `find(i)`.

Got the commit here: https://github.com/benthosdev/benthos/commit/8962251c099c9169fa1457959162f896a7bca165

**Comment by mihaitodor** [comment]
Interesting, thanks for the quick fix @Jeffail 😘 

I believe I used the `filter()` method as inspiration when I added these. However, that one is a bit odd, because I can do this:

```coffee
root = [true,false].map_each(x -> [1,2].filter(x))
```

as well as this:

```coffee
root = [true,false].map_each(x -> [1,2].filter(y -> x))
```
