### ISSUE TITLE
Extract tracing information for NATS input

### ISSUE THREAD

**Issue by mattpgray** [benthosdev/benthos#2153]
I have a simple benthos configuration that is using nats as an input, and I would like to be able to extract the tracing information from the nats request. The incoming nats message has the opentelemetry `traceparent` and `tracestate` headers for propagating the tracing information.

Would it be possible to add support for extracting the tracing information from the nats headers?

I would be happy to submit a PR if this seems reasonable.

**Comment by Jeffail** [comment]
Hey @mattpgray, sounds good, I've added an experimental general purpose config block for enabling this back when people wanted tracers from kafka but there was no general standard for it (https://www.benthos.dev/docs/components/inputs/kafka#extract_tracing_map). We can either do things automagically behind the scenes following the traditional headers or reuse the kafka bit to make things more generally applicable, that'd allow you to extract tracers using headers or from data within the payloads itself depending on the situation.

If you're interested in working on it then and want to reuse the kafka bit then it's here: https://github.com/benthosdev/benthos/blob/main/internal/component/input/span/reader.go, however it'll need to be reworked to use the new public APIs in order to work with the nats components. Luckily I am just about to finish that work in the next day or so.

**Comment by mattpgray** [comment]
Great, thanks @Jeffail. I will wait for you to finish the work on the span reader and then submit a PR for the nats implementation.
