### ISSUE TITLE
Consider accepting support through Open Collective

### ISSUE THREAD

**Issue by nwest1** [benthosdev/benthos#2344]
The organization I work for has finally started a fund to support the open source projects that we use. Unfortunately, we only are able to contribute to projects that accept funds through https://opencollective.com/

I'd love to advocate for contributions on your behalf.

**Comment by Jeffail** [comment]
Hey @nwest1, thanks for pointing this out, it was pretty easy to set up so I've made an account: https://opencollective.com/benthos, fingers crossed!

**Comment by Jeffail** [comment]
Hey @nwest1, out of interest why are you exclusively using open collective? I'm asking because it seems as though there's no way for me to opt out of their collective and that means they extract a whopping 10% of all donations (on top of the payment processing fees) which means I receive significantly less than through github sponsors.

**Comment by nwest1** [comment]
From what I understand, it's due to our accounting department and the transparency that opencollective provides. Just to note: it's not me making these decisions - I'm just the messenger :)
